@startuml
left to right direction
skinparam handwritten true
allow_mixing

actor User
boundary "Driver Selection View" as GUI
control "Driver Controller" as CTRL
entity "Driver List" as DRIVERS
entity "Active Session" as SESSION

User -- GUI : Selects Drivers
GUI -- CTRL : Request Driver List
CTRL -- SESSION : Get Current Session
CTRL -- DRIVERS : Load/Validate Drivers
@enduml
