@startuml
left to right direction
allow_mixing

actor User
boundary "Tyre Stint View" as GUI
control "Tyre Strategy Controller" as CTRL
entity "Stint Data" as STINT
entity "Tyre Compound Info" as TYRE
actor "FastF1 API" as API

User -- GUI : Requests Tyre Strategy
GUI -- CTRL : Load Strategy
CTRL -- API : Request Stint Data
CTRL -- STINT : Store Stint Data
CTRL -- TYRE : Resolve Colors
@enduml
